In [32]:
import numpy as np
def sigmoid(x):
        return 1 / (1 + np.exp(-x))

In [9]:
a = np.array([[1,2,3]])

In [27]:
b = np.array([[1,2,3], [2,3,4]])
c = np.array([[3],[4],[5]])
c


array([[3],
       [4],
       [5]])

In [17]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
a * b

array([[ 1,  4,  9],
       [ 2,  6, 12]])

In [19]:
b * a


array([[ 1,  4,  9],
       [ 2,  6, 12]])

In [23]:
b * c.T


array([[ 3,  8, 15],
       [ 6, 12, 20]])

In [24]:
a.shape

(1, 3)

In [40]:
b.T.shape

(3, 2)

In [26]:
c.shape

(3, 1)

In [47]:
np.dot(b,c)

array([[26],
       [38]])

In [33]:
sigmoid(b)

array([[ 0.73105858,  0.88079708,  0.95257413],
       [ 0.88079708,  0.95257413,  0.98201379]])